### ISSUE TITLE
Custom configuration

### ISSUE THREAD

**Issue by callum** [reapp/reapp-pack#2]
I have the following in `config/build.config.js`

``` js
var pack = require('reapp-pack');

module.exports = pack({
  entry: './app/app.js',
  devtool: 'source-map',
  target: 'web',
  env: 'production',
  debug: true,
  separateStylesheet: true
});
```

The config file is loaded fine but is discarded with this error:

```
No user config found...
[TypeError: Arguments to path.join must be strings]
```

[It falls through this try/catch when it shouldn't.](https://github.com/reapp/reapp/blob/master/lib/findConfig.js) It should properly default to the current directory without throwing that error.

Specifying `config.dir` to the above config as `process.cwd()` it then fails to load `6to5-loader` when building.

I'm finding it particularly difficult to customise the build step using Reapp. Is this something that can be made easier? My particular use case is that I want to add a number of additional plugins to Webpack. I would also like to know how to customise the output directory to be something other than `./build`. Can you advise on those?

**Comment by natew** [comment]
Awesome, was waiting for this ticket. This is something that needs to be worked on. reapp-pack is meant as a guide to get people started, but everyone has different preferences.

In the future I'd like to see it almost as a universal `webpack-config-generator`, but really then it's just another layer of abstraction on top of webpack configs themselves, so theres some thought into how to balance that.

I would love to see a PR for allowing people to add plugins and loaders. I think those are common things, but of course that's not entirely simple because you may want to `add` or `replace` them.

Anyway, in time I'll iterate on this and try and bring all that stuff in. Would like to hear other peoples thoughts on this.

**Comment by natew** [comment]
Also for an example of an app that doesn't use the CLI at all but does use reapp-pack and reapp-server, see the [hacker news app](https://github.com/reapp/hacker-news-app)

**Comment by callum** [comment]
Looks like hacker-news-app has some issues too. After installing deps and running `npm run build` I get:

```
Had warnings:
./app/routes.js
Critical dependencies:
6:16-23 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./app/routes.js 6:16-23 


./app ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./app ^\.\/.*$ 


./app ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./app ^\.\/.*$ 



undefined '\n\n'
Had errors:
./~/reapp-routes/react-router/RoutedViewListMixin.js
Module not found: Error: Cannot resolve module 'react-router/mixins/RouteHandler'
```

Similar issues using dev server with `npm start`.

```
WARNING in ./app/routes.js
Critical dependencies:
8:16-23 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./app/routes.js 8:16-23

ERROR in ./~/reapp-routes/react-router/RoutedViewListMixin.js
Module not found: Error: Cannot resolve module 'react-router/mixins/RouteHandler' in /Users/x/hacker-news-app/node_modules/reapp-routes/react-router
 @ ./~/reapp-routes/react-router/RoutedViewListMixin.js 9:24-67
```

Is this likely to be an issue with my setup?

**Comment by natew** [comment]
Looks like you need to update your dependencies, can you run `npm outdated`, and update all the reapp packages, try again?

**Comment by natew** [comment]
Closing unless further errors noticed.
